### ISSUE TITLE
Heighten Cash Monitoring CSV

### ISSUE THREAD

**Issue by ericks24** [department-of-veterans-affairs/gibct-data-service#163]
I pulled new Heighten Cash Monitoring csv file from Dept of Education and uploaded it on the Data Service. I Build New Data and push everything to Production. The Data Service System is not displaying Caution Flag for  any of the schools listed on Heighten Cash Monitoring list. The Heighten Cash Monitoring csv is in the correct format was upload successfully to the Data Service. EDU need this issue fixed as soon as possible.

**Comment by mphprogrammer** [comment]
@ericks24 - Thanks, I am going to look into it. (1) Did you push straight to production or push to staging (GIBCT preview) and then to production? (2) If you pushed to staging and then to production - do you see the flags on staging but not on production? (3) I'll need you to send me all the CSVs (I know this is a huge undertaking but I'll need to reproduce the problem).

**Comment by mphprogrammer** [comment]
@ericks24 (adding @ayaleloehr for context) - which schools in particular? I checked in the production GIBCT for ATHENS TECHNICAL COLLEGE which showed a caution flag. However, ALABAMA STATE UNIVERSITY did not show a caution flag and should have...

**Comment by mphprogrammer** [comment]
I've pushed to the GIBCT preview and ALABAMA STATE UNIVERSITY does NOT have a caution flag, despite the fact that it does in the exported CSV.

**Comment by saintsoup52** [comment]
Not sure if this has any affect... but the EXCEL version of the HCM file ED posted has some weird formatting issues, e.g., the first 12 rows are frozen (versus the usual first 4 rows).

Otherwise the two files appear to be the same to me.

Sometimes ED uses a weird excel formatting trick to add "0"'s at the beginning of the OPE ID, which only appear to the user in excel but aren't really there.

Just some thoughts.

**Comment by mphprogrammer** [comment]
@saintsoup52 spot on - I found that too, and it was a simple justification issue with ope ids. @ericks24 Once pushed to production (later today) would you be able to reload the HCM csv, build, and push to preview to examine the output? I've done a cursory check, and it looks good to me: I checked sample schools in the HCM to see that they had caution flags in the exported data.csv, and also checked that some schools that previously had flags that are no longer in the HCM csv no longer have them.

**Comment by mphprogrammer** [comment]
@ericks24 Feel free to use and push to preview... Let me know if the data is correct for HCM.

**Comment by ericks24** [comment]
@mphprogrammer  Sorry , I was on vacation all last week. I clicked Build New Data.csv and pushed to preview data. I am still not getting any of the schools to reflect the Heightened Cash Monitoring Caution Flag from the new HCM csv file.

**Comment by mphprogrammer** [comment]
@ericks24 You are going to have to reload the accreditations, complaints, 8 keys, hcm, mou, scorecard, and crosswalk csvs (to be safe). This is because the ope6 is built from the ope when a csv file is loaded, and I do not know if the other csvs dropped leading 0s.

**Comment by ericks24** [comment]
@mphprogrammer  Thanks Marc. I am going to reload all the csv files this morning and let you know the results.

**Comment by mphprogrammer** [comment]
@ericks24 Have you pushed to production today?

**Comment by ericks24** [comment]
@mphprogrammer Sorry for late response. Everything is working now as expected. Thanks for your hard work and guidance with this issue
