### ISSUE TITLE
Data Discrepancy: Approved Weams files ...

### ISSUE THREAD

**Issue by mphprogrammer** [department-of-veterans-affairs/gibct-data-service#216]
The new GIDS Institution database is about 10% smaller. This seems to be due to the code that marks an institution as approved. According to the logic, approval requires:
* At least one of: `institution_of_higher_learning_indicator`,`ojt_indicator`, `correspondence_indicator`, `flight_indicator`, or `non_college_degree_indicator` to be `true`
* The `poo_status` to be `aprvd`
* The `applicable_law_code` cannot be: `educational institution is not approved` or `educational institution is approved for chapter 31 only`.

This is a sample Weam discrepancy: 
```
#<Weam id: 104924, facility_code: "10027633", 
institution: "VETERANS HEALTH ADMINISTRATION VAMC SALISBURY CH31...", 
city: "salisbury", state: "NC", zip: "28144", country: "usa", bah: 1158, poe: false, yr: false,
va_highest_degree_offered: nil, institution_type_name: "ojt", flight: false, 

correspondence: false, accredited: false, 
ojt_indicator: false, 
correspondence_indicator: false, 
flight_indicator: false, 
non_college_degree_indicator: nil, 
institution_of_higher_learning_indicator: false, 
poo_status: "aprvd", 
applicable_law_code: "educational institution is approved for all chapters", 

approved: nil, address_1: "1601 brenner ave", address_2: nil, address_3: nil, cross: nil, 
ope: nil, ope6: nil, created_at: "2017-03-07 17:04:15", updated_at: "2017-03-07 17:04:15">
```

By my reckoning - this should not be output in the institution.csv (data.csv) as this is a non-approved school. The new GIDS does not include it, but the old GIDS does. @saintsoup52, can I get a ruling?

**Comment by mphprogrammer** [comment]
Wait ... @saintsoup52  is it possible that files were uploaded, but the preview version not built. Would it be a regular practice to upload new files, but not build the database them right away? There was a weams file that was uploaded today...

**Comment by saintsoup52** [comment]
It is definitely possible... I don't do that but some of our friends at EDU may do it to start the staging and then stop.

As for the the example above... you are correct that should not appear to be an approved school because there are no approved programs.

**Comment by mphprogrammer** [comment]
There seem to be about 22 such records that differ, not a biggee but that was one of them.

**Comment by patrickvinograd** [comment]
@mphprogrammer The record you included above was suffering from the issue fixed in #218. - Note above it says `non_college_degree_indicator: nil, ` - but in weams.csv, that column is Yes, so this institution should be included.

**Comment by patrickvinograd** [comment]
Also note "approved" is `nil`, not `false`, because `false || nil = nil` in ruby.

**Comment by mphprogrammer** [comment]
@patrickvinograd Yes - the key thing here is the indicators != true.

**Comment by mphprogrammer** [comment]
OK - Verified on a row by row basis comparing New GIDS with the Weams.csv to look for discrepancies. Comparing an excel computation based on the above criteria, and the actual data in the gids database, all weams approved schools are in the data, and all non-approved schools are not. @saintsoup52 @saneshark would like to close this. You can verify my computations in the verify.xlsx spreadsheet: https://github.com/department-of-veterans-affairs/gibct-data-service/blob/v2-refactor-verify/sample_csvs/verify.xlsx

**Comment by saintsoup52** [comment]
I am still seeing 9 more facility codes from the new data service then the older version.

I think this issue is because EDU was updating some of the schools by hand and therefore there must be a versioning issue. 

All of the 9 schools are related and are currently closed but not reflected as such in WEAMS.

**Comment by mphprogrammer** [comment]
@saintsoup52 I just loaded the old GIDS software and used the new GIDS CSVS (Weams, crosswalk, etch) to produce the data.csv - the number of facility codes matches exactly. They must have uploaded Weams on 3/7 but not built a new Data.csv...

**Comment by mphprogrammer** [comment]
Compared old and new GIDS using same Weam.csv - no discrepancy found. Moving this issue to Done.
